### PR TITLE
Restoring app-module-path

### PR DESCRIPTION
**Pull request by mitar**
Sorry for this. I really thought this will just work and local testing didn't catch it. Sorry for doing all this work for you. :-(

### CODE REVIEW

**Comment by mitar** [comment]
And I suggest that we reopen #15.

**Comment by juliancwirko** [comment]
Don't worry, the idea was worth trying. Hope it will be possible soon :)

**Comment by mitar** [comment]
See https://github.com/meteor/meteor/issues/9865 for more details.

**Comment by eybarta** [comment]
hey guys, thanks for your work.. have I missed any progress on this? I'm still getting the PostCSS errors during build and hot reloads, am I doing something wrong or is this still an issue? thx!

**Pull request merged**
